apiVersion: v1
kind: Secret
metadata:
  name: zenith-x-secrets
type: Opaque
data:
  # Base64 encoded MONGODB_URI
  # Echo -n "your-mongodb-uri" | base64
  MONGODB_URI: REPLACE_WITH_BASE64_MONGODB_URI
